set(headers ${headers}
	src/Core/Config.hpp
	src/Core/Console/ConsoleCommands.hpp
	src/Core/Core.hpp
	src/Core/Event/Event.hpp
	src/Core/Event/EventHandler.hpp
	src/Core/Locale/Locale.hpp
	src/Core/Locale/LocaleManager.hpp
	src/Core/Locale/LocalePackage.hpp
	src/Core/Locale/LocaleStrings.hpp
	src/Core/Menu/Items/ItemForm.hpp
	src/Core/Menu/Items/ItemPlugin.hpp
	src/Core/Menu/JournalMenu.hpp
	src/Core/Menu/MainMenu.hpp
	src/Core/Menu/PluginExplorer.hpp
	src/Core/Menu/PluginExplorerHandler.hpp
	src/Core/Menu/PluginExplorerMenu.hpp
	src/General/Input.hpp
	src/General/Script.hpp
	src/General/Singleton.hpp
	src/PCH.hpp
	src/Scaleform/Array.hpp
	src/Scaleform/CLIK/GFx/Controls/Button.hpp
	src/Scaleform/CLIK/GFx/Controls/ButtonBar.hpp
	src/Scaleform/CLIK/GFx/Controls/CoreList.hpp
	src/Scaleform/CLIK/GFx/Controls/DropdownMenu.hpp
	src/Scaleform/CLIK/GFx/Controls/ScrollingList.hpp
	src/Scaleform/CLIK/GFx/Controls/Slider.hpp
	src/Scaleform/CLIK/GFx/Controls/TextInput.hpp
	src/Scaleform/CLIK/GFx/Core/UIComponent.hpp
	src/Scaleform/Common/Item.hpp
	src/Scaleform/Common/ItemList.hpp
	src/Scaleform/MovieClip.hpp
	src/Scaleform/Object.hpp
	src/Scaleform/System/Assert.hpp
	src/Scaleform/System/Function.hpp
	src/Scaleform/System/Logger.hpp
	src/Scaleform/TextField.hpp
)
